
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Xabbo.Messages.Nitro;

/// <summary>
/// Extracted from Nitro client version WIN63-202410132312-548085391 from BSS Client API.
/// </summary>
public static class In {

    // Private static list to store all Identifier instances
    private static readonly List<Identifier> _allIdentifiers;

    /// <summary>
    /// Gets a read-only list of all Identifier instances defined in this class.
    /// </summary>
    public static IReadOnlyList<Identifier> AllIdentifiers => _allIdentifiers.AsReadOnly();

    // Static constructor to initialize the list using reflection
    static In()
    {
        _allIdentifiers = new List<Identifier>();
        // Get all public static readonly fields of type Identifier in this class
        FieldInfo[] fields =
            typeof(In).GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy);

        foreach (var field in fields)
        {
            if (field.FieldType == typeof(Identifier))
            {
                // Get the value of the field
                var identifier = (Identifier)field.GetValue(null)!;
                _allIdentifiers.Add(identifier);
            }
        }
    }


    private static Identifier _([CallerMemberName]string? name = null, short? header = null)
    {
        ArgumentNullException.ThrowIfNull(name, nameof(name));
        return new Identifier(ClientType.Nitro, Direction.In, name, header);
    }

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

    public static readonly Identifier Achievement_List = _(header: 1134);
    public static readonly Identifier Authenticated = _(header: 41);
    public static readonly Identifier Availability_Status = _(header: 3209);
    public static readonly Identifier Builders_Club_Expired = _(header: 3997);
    public static readonly Identifier Club_Offers = _(header: 3312);
    public static readonly Identifier Catalog_Page = _(header: 1763);
    public static readonly Identifier Catalog_Page_List = _(header: 2612);
    public static readonly Identifier Catalog_Purchase_Ok = _(header: 584);
    public static readonly Identifier Catalog_Purchase_Error = _(header: 1721);
    public static readonly Identifier Catalog_Purchase_Not_Allowed = _(header: 3186);
    public static readonly Identifier Product_Offer = _(header: 1303);
    public static readonly Identifier Limited_Sold_Out = _(header: 1631);
    public static readonly Identifier Catalog_Published = _(header: 1318);
    public static readonly Identifier Cfh_Result_Message = _(header: 1873);
    public static readonly Identifier Latency = _(header: 3831);
    public static readonly Identifier Ping = _(header: 1272);
    public static readonly Identifier Hotel_Campaign = _(header: 1701);
    public static readonly Identifier Hotel_News = _(header: 1452);
    public static readonly Identifier Hotel_View = _(header: 378);
    public static readonly Identifier Bundle_Discount_Ruleset = _(header: 1462);
    public static readonly Identifier First_Login_Of_Day = _(header: 3915);
    public static readonly Identifier Furniture_Aliases = _(header: 2274);
    public static readonly Identifier FloorItem_Update_Status = _(header: 2120);
    public static readonly Identifier Floor_Furni_List = _(header: 473);
    public static readonly Identifier Floor_Add = _(header: 2057);
    public static readonly Identifier Floor_Remove = _(header: 1096);
    public static readonly Identifier Floor_Update = _(header: 174);
    public static readonly Identifier Furniture_Itemdata = _(header: 2490);
    public static readonly Identifier Furniture_State = _(header: 2042);
    public static readonly Identifier Furniture_Group_Context_Menu_Info = _(header: 1215);
    public static readonly Identifier Furniture_Postit_Sticky_Pole_Open = _(header: 1112);
    public static readonly Identifier Game_Center_Achievements = _(header: 2244);
    public static readonly Identifier Game_Center_Game_List = _(header: 655);
    public static readonly Identifier Game_Center_Status = _(header: 1856);
    public static readonly Identifier Gamestatusmessage = _(header: 3739);
    public static readonly Identifier Gameachievements = _(header: 3516);
    public static readonly Identifier Gameinvite = _(header: 3619);
    public static readonly Identifier Joiningqueuefailed = _(header: 1663);
    public static readonly Identifier Joinedqueuemessage = _(header: 1696);
    public static readonly Identifier Leftqueue = _(header: 3232);
    public static readonly Identifier Load_Game_Url = _(header: 1954);
    public static readonly Identifier Loadgame = _(header: 1989);
    public static readonly Identifier Unloadgame = _(header: 2607);
    public static readonly Identifier Achievementresolutioncompleted = _(header: 502);
    public static readonly Identifier Achievementresolutionprogress = _(header: 382);
    public static readonly Identifier Achievementresolutions = _(header: 254);
    public static readonly Identifier Generic_Alert = _(header: 3346);
    public static readonly Identifier Moderator_Message = _(header: 2645);
    public static readonly Identifier Generic_Error = _(header: 1321);
    public static readonly Identifier Gift_Wrapper_Config = _(header: 3609);
    public static readonly Identifier Group_Badges = _(header: 2999);
    public static readonly Identifier Group_Create_Options = _(header: 1799);
    public static readonly Identifier Group_Forum_Data = _(header: 779);
    public static readonly Identifier Group_Forum_List = _(header: 1045);
    public static readonly Identifier Group_Forum_Threads = _(header: 1906);
    public static readonly Identifier Group_Forum_Post = _(header: 600);
    public static readonly Identifier Group_Forum_Post_Thread = _(header: 2766);
    public static readonly Identifier Group_Forum_Thread_Messages = _(header: 1888);
    public static readonly Identifier Group_Forum_Unread_Count = _(header: 823);
    public static readonly Identifier Group_Forum_Update_Message = _(header: 2687);
    public static readonly Identifier Group_Forum_Update_Thread = _(header: 1597);
    public static readonly Identifier Group_Info = _(header: 248);
    public static readonly Identifier Group_List = _(header: 708);
    public static readonly Identifier Group_Member = _(header: 2666);
    public static readonly Identifier Group_Members = _(header: 1252);
    public static readonly Identifier Group_Members_Refresh = _(header: 3160);
    public static readonly Identifier Group_Member_Remove_Confirm = _(header: 213);
    public static readonly Identifier Group_Purchased = _(header: 2199);
    public static readonly Identifier Group_Settings = _(header: 3764);
    public static readonly Identifier Group_Badge_Parts = _(header: 2138);
    public static readonly Identifier Item_Dimmer_Settings = _(header: 444);
    public static readonly Identifier Item_Stack_Helper = _(header: 1190);
    public static readonly Identifier Item_Wall_list = _(header: 3120);
    public static readonly Identifier Item_Wall_Add = _(header: 3864);
    public static readonly Identifier Item_Wall_Remove = _(header: 139);
    public static readonly Identifier Item_Wall_Update = _(header: 1052);
    public static readonly Identifier Marketplace_Config = _(header: 802);
    public static readonly Identifier Messenger_Accept_Friends = _(header: 1025);
    public static readonly Identifier Messenger_Chat = _(header: 3791);
    public static readonly Identifier Messenger_Find_Friends = _(header: 631);
    public static readonly Identifier Messenger_Follow_Failed = _(header: 2441);
    public static readonly Identifier Messenger_Friend_Notification = _(header: 688);
    public static readonly Identifier Messenger_Friends = _(header: 2399);
    public static readonly Identifier Messenger_Init = _(header: 2497);
    public static readonly Identifier Messenger_Instance_Message_Error = _(header: 1472);
    public static readonly Identifier Messenger_Invite = _(header: 678);
    public static readonly Identifier Messenger_Invite_Error = _(header: 2617);
    public static readonly Identifier Messenger_Message_Error = _(header: 2127);
    public static readonly Identifier Messenger_Minimail_Count = _(header: 3747);
    public static readonly Identifier Messenger_Minimail_New = _(header: 2421);
    public static readonly Identifier Messenger_Relationships = _(header: 3871);
    public static readonly Identifier Messenger_Request = _(header: 951);
    public static readonly Identifier Messenger_Request_Error = _(header: 2127);
    public static readonly Identifier Messenger_Requests = _(header: 2752);
    public static readonly Identifier Messenger_Search = _(header: 2701);
    public static readonly Identifier Messenger_Update = _(header: 100);
    public static readonly Identifier Moderation_Report_Disabled = _(header: 2014);
    public static readonly Identifier Moderation_Tool = _(header: 2998);
    public static readonly Identifier Moderation_User_Info = _(header: 3683);
    public static readonly Identifier Motd_Messages = _(header: 2606);
    public static readonly Identifier Navigator_Categories = _(header: 462);
    public static readonly Identifier Navigator_Collapsed = _(header: 3984);
    public static readonly Identifier Navigator_Event_Categories = _(header: 745);
    public static readonly Identifier Navigator_Lifted = _(header: 1392);
    public static readonly Identifier Navigator_Metadata = _(header: 1302);
    public static readonly Identifier Navigator_Open_Room_Creator = _(header: 2496);
    public static readonly Identifier Navigator_Search = _(header: 813);
    public static readonly Identifier Navigator_Searches = _(header: 2393);
    public static readonly Identifier Navigator_Settings = _(header: 2981);
    public static readonly Identifier Thumbnail_Update_Result = _(header: 1663);
    public static readonly Identifier Can_Create_Room = _(header: 2744);
    public static readonly Identifier Categories_With_Visitor_Count = _(header: 3271);
    public static readonly Identifier Competition_Rooms_Data = _(header: 255);
    public static readonly Identifier Converted_Room_Id = _(header: 320);
    public static readonly Identifier Get_Guest_Room_Result = _(header: 3187);
    public static readonly Identifier Notification_Dialog = _(header: 1900);
    public static readonly Identifier Pet_Figure_Update = _(header: 2376);
    public static readonly Identifier Pet_Info = _(header: 756);
    public static readonly Identifier Recycler_Prizes = _(header: 1283);
    public static readonly Identifier Room_Ban_List = _(header: 3863);
    public static readonly Identifier Room_Ban_Remove = _(header: 2839);
    public static readonly Identifier Room_Created = _(header: 776);
    public static readonly Identifier Room_Doorbell = _(header: 2660);
    public static readonly Identifier Room_Doorbell_Accepted = _(header: 1915);
    public static readonly Identifier Room_Doorbell_Rejected = _(header: 2384);
    public static readonly Identifier Room_Enter = _(header: 1464);
    public static readonly Identifier Room_Enter_Error = _(header: 1703);
    public static readonly Identifier Room_Forward = _(header: 732);
    public static readonly Identifier Room_Height_Map = _(header: 2604);
    public static readonly Identifier Room_Height_Map_Update = _(header: 2927);
    public static readonly Identifier Room_Info = _(header: 2974);
    public static readonly Identifier Room_Info_Owner = _(header: 3277);
    public static readonly Identifier Room_Model = _(header: 2434);
    public static readonly Identifier Room_Model_Blocked_Tiles = _(header: 3103);
    public static readonly Identifier Room_Model_Door = _(header: 885);
    public static readonly Identifier Room_Model_Name = _(header: 329);
    public static readonly Identifier Room_Muted = _(header: 3471);
    public static readonly Identifier Room_Mute_User = _(header: 3674);
    public static readonly Identifier RoomProperty = _(header: 3235);
    public static readonly Identifier Room_Queue_Status = _(header: 2358);
    public static readonly Identifier Room_Rights = _(header: 2613);
    public static readonly Identifier Room_Rights_Clear = _(header: 2407);
    public static readonly Identifier Room_Rights_List = _(header: 2269);
    public static readonly Identifier Room_Rights_List_Add = _(header: 3288);
    public static readonly Identifier Room_Rights_Owner = _(header: 1031);
    public static readonly Identifier Slide_Object_Bundle = _(header: 3371);
    public static readonly Identifier Room_Score = _(header: 1798);
    public static readonly Identifier Room_Settings = _(header: 911);
    public static readonly Identifier Room_Settings_Chat = _(header: 2494);
    public static readonly Identifier Room_Settings_Save = _(header: 2758);
    public static readonly Identifier Room_Settings_Save_Error = _(header: 3462);
    public static readonly Identifier Room_Info_Updated = _(header: 1328);
    public static readonly Identifier Room_Spectator = _(header: 1223);
    public static readonly Identifier Room_Visualization_Settings = _(header: 2109);
    public static readonly Identifier Info_Feed_Enable = _(header: 893);
    public static readonly Identifier Security_Machine = _(header: 2270);
    public static readonly Identifier Mystery_Box_Keys = _(header: 70);
    public static readonly Identifier Trade_Accepted = _(header: 3615);
    public static readonly Identifier Trade_Closed = _(header: 1166);
    public static readonly Identifier Trade_Completed = _(header: 3731);
    public static readonly Identifier Trade_Confirmation = _(header: 3902);
    public static readonly Identifier Trade_List_Item = _(header: 1243);
    public static readonly Identifier Trade_Not_Open = _(header: 1506);
    public static readonly Identifier Trade_Open = _(header: 425);
    public static readonly Identifier Trade_Open_Failed = _(header: 1589);
    public static readonly Identifier Trade_You_Not_Allowed = _(header: 1419);
    public static readonly Identifier Users = _(header: 3315);
    public static readonly Identifier UserNameChanged = _(header: 1232);
    public static readonly Identifier Chat = _(header: 2398);
    public static readonly Identifier Shout = _(header: 430);
    public static readonly Identifier Whisper = _(header: 2814);
    public static readonly Identifier Dance = _(header: 3427);
    public static readonly Identifier Effect = _(header: 692);
    public static readonly Identifier Expression = _(header: 2783);
    public static readonly Identifier Hand_Item = _(header: 3138);
    public static readonly Identifier Idle = _(header: 1021);
    public static readonly Identifier UserChange = _(header: 3606);
    public static readonly Identifier Number = _(header: 379);
    public static readonly Identifier UserRemove = _(header: 2198);
    public static readonly Identifier UserUpdate = _(header: 2658);
    public static readonly Identifier Typing = _(header: 13);
    public static readonly Identifier Unseen_Items = _(header: 2050);
    public static readonly Identifier User_Achievement_Score = _(header: 2006);
    public static readonly Identifier User_Badges = _(header: 2977);
    public static readonly Identifier User_Badges_Add = _(header: 3423);
    public static readonly Identifier User_Badges_Current = _(header: 1978);
    public static readonly Identifier User_Bot_Remove = _(header: 2075);
    public static readonly Identifier User_Bots = _(header: 824);
    public static readonly Identifier User_Change_Name = _(header: 1709);
    public static readonly Identifier User_Clothing = _(header: 3091);
    public static readonly Identifier User_Credits = _(header: 1860);
    public static readonly Identifier User_Currency = _(header: 2791);
    public static readonly Identifier Activity_Point_Notification = _(header: 48);
    public static readonly Identifier User_Effects = _(header: 365);
    public static readonly Identifier User_Favorite_Room = _(header: 67);
    public static readonly Identifier User_Favorite_Room_Count = _(header: 2761);
    public static readonly Identifier User_Figure = _(header: 1042);
    public static readonly Identifier User_Furniture_list = _(header: 1332);
    public static readonly Identifier User_Furniture_Add = _(header: 275);
    public static readonly Identifier User_Furniture_Postit_Placed = _(header: 2046);
    public static readonly Identifier User_Furniture_Refresh = _(header: 1206);
    public static readonly Identifier User_Furniture_Remove = _(header: 1051);
    public static readonly Identifier User_Home_Room = _(header: 3323);
    public static readonly Identifier Room_Event_Cancel = _(header: 1559);
    public static readonly Identifier Room_Event = _(header: 1845);
    public static readonly Identifier User_Ignored = _(header: 403);
    public static readonly Identifier User_Ignored_Result = _(header: 369);
    public static readonly Identifier User_Info = _(header: 1950);
    public static readonly Identifier User_Outfits = _(header: 1343);
    public static readonly Identifier User_Perks = _(header: 3067);
    public static readonly Identifier User_Permissions = _(header: 3918);
    public static readonly Identifier User_Pet_Add = _(header: 1972);
    public static readonly Identifier User_Pet_Remove = _(header: 1911);
    public static readonly Identifier User_Pets = _(header: 1380);
    public static readonly Identifier User_Profile = _(header: 2505);
    public static readonly Identifier User_Respect = _(header: 3419);
    public static readonly Identifier User_Settings = _(header: 2468);
    public static readonly Identifier User_Subscription = _(header: 3531);
    public static readonly Identifier User_Wardrobe_Page = _(header: 1343);
    public static readonly Identifier Wired_Action = _(header: 2530);
    public static readonly Identifier Wired_Condition = _(header: 2300);
    public static readonly Identifier Wired_Error = _(header: 2626);
    public static readonly Identifier Wired_Open = _(header: 2242);
    public static readonly Identifier Wired_Reward = _(header: 1948);
    public static readonly Identifier Wired_Save = _(header: 2560);
    public static readonly Identifier Wired_Trigger = _(header: 2194);
    public static readonly Identifier Playing_Game = _(header: 232);
    public static readonly Identifier Remove_Bot_From_Inventory = _(header: 2075);
    public static readonly Identifier Add_Bot_To_Inventory = _(header: 535);
    public static readonly Identifier Achievement_Progressed = _(header: 3653);
    public static readonly Identifier Modtool_Room_Info = _(header: 3048);
    public static readonly Identifier Modtool_User_Chatlog = _(header: 3607);
    public static readonly Identifier Modtool_Room_Chatlog = _(header: 1692);
    public static readonly Identifier Modtool_Visited_Rooms_User = _(header: 1361);
    public static readonly Identifier Moderator_Action_Result = _(header: 1649);
    public static readonly Identifier Issue_Deleted = _(header: 704);
    public static readonly Identifier Issue_Info = _(header: 701);
    public static readonly Identifier Issue_Pick_Failed = _(header: 1925);
    public static readonly Identifier Cfh_Chatlog = _(header: 3450);
    public static readonly Identifier Moderator_Tool_Preferences = _(header: 960);
    public static readonly Identifier Lovelock_Furni_Start = _(header: 1749);
    public static readonly Identifier Lovelock_Furni_Friend_Confirmed = _(header: 2534);
    public static readonly Identifier Lovelock_Furni_Finished = _(header: 2139);
    public static readonly Identifier Gift_Receiver_Not_Found = _(header: 2675);
    public static readonly Identifier Gift_Opened = _(header: 3166);
    public static readonly Identifier Flood_Control = _(header: 3327);
    public static readonly Identifier Remaining_Mute = _(header: 3674);
    public static readonly Identifier User_Effect_List = _(header: 365);
    public static readonly Identifier User_Effect_List_Add = _(header: 2731);
    public static readonly Identifier User_Effect_List_Remove = _(header: 2614);
    public static readonly Identifier User_Effect_Activate = _(header: 1457);
    public static readonly Identifier Club_Gift_Info = _(header: 3950);
    public static readonly Identifier Redeem_Voucher_Error = _(header: 2857);
    public static readonly Identifier Redeem_Voucher_Ok = _(header: 1402);
    public static readonly Identifier In_Client_Link = _(header: 78);
    public static readonly Identifier Bot_Command_Configuration = _(header: 1831);
    public static readonly Identifier Hand_Item_Received = _(header: 618);
    public static readonly Identifier Pet_Placing_Error = _(header: 542);
    public static readonly Identifier Bot_Error = _(header: 1670);
    public static readonly Identifier Marketplace_Sell_Item = _(header: 1503);
    public static readonly Identifier Marketplace_Item_Stats = _(header: 1310);
    public static readonly Identifier Marketplace_Own_Items = _(header: 1309);
    public static readonly Identifier Marketplace_Cancel_Sale = _(header: 3991);
    public static readonly Identifier Marketplace_Item_Posted = _(header: 1664);
    public static readonly Identifier Marketplace_Items_Searched = _(header: 1766);
    public static readonly Identifier Marketplace_After_Order_Status = _(header: 2661);
    public static readonly Identifier Catalog_Receive_Pet_Breeds = _(header: 3709);
    public static readonly Identifier Catalog_Approve_Name_Result = _(header: 2918);
    public static readonly Identifier Objects_Data_Update = _(header: 339);
    public static readonly Identifier Pet_Experience = _(header: 713);
    public static readonly Identifier Community_Goal_Vote_Event = _(header: 1194);
    public static readonly Identifier Promo_Articles = _(header: 1452);
    public static readonly Identifier Community_Goal_Earned_Prizes = _(header: 1931);
    public static readonly Identifier Community_Goal_Progress = _(header: 3411);
    public static readonly Identifier Concurrent_Users_Goal_Progress = _(header: 1722);
    public static readonly Identifier Quest_Daily = _(header: 142);
    public static readonly Identifier Quest_Cancelled = _(header: 3397);
    public static readonly Identifier Quest_Completed = _(header: 1880);
    public static readonly Identifier Community_Goal_Hall_Of_Fame = _(header: 1140);
    public static readonly Identifier Epic_Popup = _(header: 1765);
    public static readonly Identifier Seasonal_Quests = _(header: 279);
    public static readonly Identifier Quests = _(header: 3532);
    public static readonly Identifier Quest = _(header: 1195);
    public static readonly Identifier Bonus_Rare_Info = _(header: 1300);
    public static readonly Identifier Craftable_Products = _(header: 1619);
    public static readonly Identifier Crafting_Recipe = _(header: 2451);
    public static readonly Identifier Crafting_Recipes_Available = _(header: 3519);
    public static readonly Identifier Crafting_Result = _(header: 1032);
    public static readonly Identifier Camera_Publish_Status = _(header: 3558);
    public static readonly Identifier Camera_Purchase_Ok = _(header: 3927);
    public static readonly Identifier Camera_Storage_Url = _(header: 2404);
    public static readonly Identifier Competition_Status = _(header: 249);
    public static readonly Identifier Init_Camera = _(header: 446);
    public static readonly Identifier Thumbnail_Status = _(header: 340);
    public static readonly Identifier Achievement_Notification = _(header: 2324);
    public static readonly Identifier Club_Gift_Notification = _(header: 1073);
    public static readonly Identifier Interstitial_Message = _(header: 918);
    public static readonly Identifier Room_Ad_Error = _(header: 3354);
    public static readonly Identifier Availability_Time = _(header: 537);
    public static readonly Identifier Hotel_Closed_And_Opens = _(header: 3152);
    public static readonly Identifier Hotel_Closes_And_Opens_At = _(header: 1508);
    public static readonly Identifier Hotel_Will_Close_Minutes = _(header: 2933);
    public static readonly Identifier Hotel_Maintenance = _(header: 3415);
    public static readonly Identifier Jukebox_Playlist_Full = _(header: 765);
    public static readonly Identifier Jukebox_Song_Disks = _(header: 1876);
    public static readonly Identifier Now_Playing = _(header: 3668);
    public static readonly Identifier Official_Song_Id = _(header: 901);
    public static readonly Identifier Playlist = _(header: 3246);
    public static readonly Identifier Playlist_Song_Added = _(header: 1210);
    public static readonly Identifier Trax_Song_Info = _(header: 1892);
    public static readonly Identifier User_Song_Disks_Inventory = _(header: 621);
    public static readonly Identifier Check_User_Name = _(header: 1686);
    public static readonly Identifier Cfh_Sanction = _(header: 115);
    public static readonly Identifier Cfh_Topics = _(header: 2010);
    public static readonly Identifier Cfh_Sanction_Status = _(header: 2801);
    public static readonly Identifier Campaign_Calendar_Data = _(header: 2169);
    public static readonly Identifier Campaign_Calendar_Door_Opened = _(header: 3934);
    public static readonly Identifier Builders_Club_Furni_Count = _(header: 1173);
    public static readonly Identifier Builders_Club_Subscription = _(header: 3997);
    public static readonly Identifier Catalog_Page_Expiration = _(header: 737);
    public static readonly Identifier Catalog_Earliest_Expiry = _(header: 3102);
    public static readonly Identifier Club_Gift_Selected = _(header: 659);
    public static readonly Identifier Target_Offer_Not_Found = _(header: 1440);
    public static readonly Identifier Target_Offer = _(header: 3435);
    public static readonly Identifier Direct_Sms_Club_Buy = _(header: 40);
    public static readonly Identifier Room_Ad_Purchase = _(header: 2394);
    public static readonly Identifier Not_Enough_Balance = _(header: 192);
    public static readonly Identifier Limited_Offer_Appearing_Next = _(header: 1792);
    public static readonly Identifier Is_Offer_Giftable = _(header: 2663);
    public static readonly Identifier Club_Extended_Offer = _(header: 3218);
    public static readonly Identifier Seasonal_Calendar_Offer = _(header: 973);
    public static readonly Identifier Competition_Entry_Submit = _(header: 180);
    public static readonly Identifier Competition_Voting_Info = _(header: 3634);
    public static readonly Identifier Competition_Timing_Code = _(header: 1701);
    public static readonly Identifier Competition_User_Part_Of = _(header: 1131);
    public static readonly Identifier Competition_No_Owned_Rooms = _(header: 2496);
    public static readonly Identifier Competition_Seconds_Until = _(header: 1357);
    public static readonly Identifier Badge_Point_Limits = _(header: 2568);
    public static readonly Identifier Badge_Request_Fulfilled = _(header: 1339);
    public static readonly Identifier Helper_Talent_Track = _(header: 1618);
    public static readonly Identifier User_Banned = _(header: 3593);
    public static readonly Identifier Bot_Received = _(header: 2656);
    public static readonly Identifier Pet_Level_Notification = _(header: 3205);
    public static readonly Identifier Pet_Received = _(header: 1530);
    public static readonly Identifier Moderation_Caution = _(header: 1496);
    public static readonly Identifier Youtube_Control_Video = _(header: 2900);
    public static readonly Identifier Youtube_Display_Playlists = _(header: 1460);
    public static readonly Identifier Youtube_Display_Video = _(header: 2724);
    public static readonly Identifier Cfh_Disabled_Notify = _(header: 2014);
    public static readonly Identifier Question = _(header: 1901);
    public static readonly Identifier Poll_Contents = _(header: 3389);
    public static readonly Identifier Poll_Error = _(header: 242);
    public static readonly Identifier Poll_Offer = _(header: 2774);
    public static readonly Identifier Question_Answered = _(header: 2775);
    public static readonly Identifier Question_Finished = _(header: 1632);
    public static readonly Identifier Cfh_Pending_Calls = _(header: 2682);
    public static readonly Identifier Guide_On_Duty_Status = _(header: 1);
    public static readonly Identifier Guide_Session_Attached = _(header: 842);
    public static readonly Identifier Guide_Session_Detached = _(header: 633);
    public static readonly Identifier Guide_Session_Ended = _(header: 2554);
    public static readonly Identifier Guide_Session_Error = _(header: 1085);
    public static readonly Identifier Guide_Session_Invited_To_Guide_Room = _(header: 3556);
    public static readonly Identifier Guide_Session_Message = _(header: 102);
    public static readonly Identifier Guide_Session_Partner_Is_Typing = _(header: 1929);
    public static readonly Identifier Guide_Session_Requester_Room = _(header: 478);
    public static readonly Identifier Guide_Session_Started = _(header: 2326);
    public static readonly Identifier Guide_Ticket_Creation_Result = _(header: 2092);
    public static readonly Identifier Guide_Ticket_Resolution = _(header: 2092);
    public static readonly Identifier Guide_Reporting_Status = _(header: 718);
    public static readonly Identifier Hotel_Merge_Name_Change = _(header: 2338);
    public static readonly Identifier Issue_Close_Notification = _(header: 581);
    public static readonly Identifier Quiz_Data = _(header: 2076);
    public static readonly Identifier Quiz_Results = _(header: 3414);
    public static readonly Identifier Cfh_Pending_Calls_Deleted = _(header: 644);
    public static readonly Identifier Cfh_Reply = _(header: 170);
    public static readonly Identifier Chat_Review_Session_Detached = _(header: 1732);
    public static readonly Identifier Chat_Review_Session_Offered_To_Guide = _(header: 3292);
    public static readonly Identifier Chat_Review_Session_Results = _(header: 1684);
    public static readonly Identifier Chat_Review_Session_Started = _(header: 281);
    public static readonly Identifier Chat_Review_Session_Voting_Status = _(header: 731);
    public static readonly Identifier Scr_Send_Kickback_Info = _(header: 38);
    public static readonly Identifier Pet_Status = _(header: 3297);
    public static readonly Identifier Group_Deactivate = _(header: 661);
    public static readonly Identifier Pet_Respected = _(header: 1098);
    public static readonly Identifier Pet_Supplement = _(header: 705);
    public static readonly Identifier Noobness_Level = _(header: 2893);
    public static readonly Identifier Can_Create_Room_Event = _(header: 2226);
    public static readonly Identifier Favorite_Group_Update = _(header: 2970);
    public static readonly Identifier No_Such_Flat = _(header: 1160);
    public static readonly Identifier Room_Settings_Error = _(header: 3978);
    public static readonly Identifier Show_Enforce_Room_Category = _(header: 3374);


#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
